export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LISTUSER_REQUEST = "LISTUSER_REQUEST";
export const LISTUSER_SUCCESS = "LISTUSER_SUCCESS";
export const LISTUSER_ERROR = "LISTUSER_ERROR";

export const LISTPOLL_REQUEST = "LISTPOLL_REQUEST";
export const LISTPOLL_SUCCESS = "LISTPOLL_SUCCESS";
export const LISTPOLL_ERROR = "LISTPOLL_ERROR";

export const DELETEPOLL_REQUEST = "DELETEPOLL_REQUEST";
export const DELETEPOLL_SUCCESS = "DELETEPOLL_SUCCESS";
export const DELETEPOLL_ERROR = "DELETEPOLL_ERROR";

export const ADDPOLL_REQUEST = "ADDPOLL_REQUEST";
export const ADDPOLL_SUCCESS = "ADDPOLL_SUCCESS";
export const ADDPOLL_ERROR = "ADDPOLL_ERROR"